import type { EventThemeName } from "@interfaces/event"
import type { IconType } from "react-icons"
import {
  FaBirthdayCake,
  FaBook,
  FaBookOpen,
  FaBriefcase,
  FaCalendar,
  FaCamera,
  FaChalkboardTeacher,
  FaChild,
  FaCode,
  FaDumbbell,
  FaFeather,
  FaFilm,
  FaFlag,
  FaFlask,
  FaFutbol,
  FaGamepad,
  FaGraduationCap,
  FaHandHoldingHeart,
  FaHandshake,
  FaHandsHelping,
  FaHeart,
  FaImage,
  FaLandmark,
  FaLanguage,
  FaLaptopCode,
  FaLaugh,
  FaLeaf,
  FaMedal,
  FaMicrophone,
  FaMountain,
  FaMusic,
  FaPaintBrush,
  FaPaw,
  FaPeace,
  FaPeopleArrows,
  FaPeopleCarry,
  FaPersonBooth,
  FaPlane,
  FaQuestion,
  FaRecycle,
  FaRegSmile,
  FaRegStar,
  FaRocket,
  FaRoute,
  FaShoppingCart,
  FaSpa,
  FaStar,
  FaStore,
  FaTheaterMasks,
  FaTrophy,
  FaTshirt,
  FaUsers,
  FaUtensils,
  FaWalking,
} from "react-icons/fa"

export const themeIconMap: Record<EventThemeName, IconType> = {
  Music: FaMusic,
  Art: FaPaintBrush,
  Sports: FaFutbol,
  Tech: FaLaptopCode,
  Food: FaUtensils,
  Networking: FaUsers,
  Health: FaHeart,
  Education: FaBook,
  Business: FaBriefcase,
  Nature: FaLeaf,
  Travel: FaPlane,
  Charity: FaHandHoldingHeart,
  Fashion: FaTshirt,
  Film: FaFilm,
  Photography: FaCamera,
  Literature: FaFeather,
  Science: FaFlask,
  Gaming: FaGamepad,
  Spirituality: FaPeace,
  Family: FaChild,
  Comedy: FaLaugh,
  Dance: FaPersonBooth,
  History: FaLandmark,
  Politics: FaLandmark,
  Environment: FaRecycle,
  Pets: FaPaw,
  Shopping: FaShoppingCart,
  Fitness: FaDumbbell,
  Theater: FaTheaterMasks,
  Crafts: FaFeather,
  Languages: FaLanguage,
  Social: FaUsers,
  Adventure: FaMountain,
  Startup: FaRocket,
  "Book Club": FaBookOpen,
  Coding: FaCode,
  Volunteering: FaHandsHelping,
  Wellness: FaSpa,
  Exhibition: FaImage,
  Tournament: FaTrophy,
  Workshop: FaChalkboardTeacher,
  Meetup: FaHandshake,
  Lecture: FaMicrophone,
  Hackathon: FaQuestion,
  Fundraiser: FaHandHoldingHeart,
  "Open Mic": FaMicrophone,
  Quiz: FaQuestion,
  Tour: FaRoute,
  Market: FaStore,
  Parade: FaWalking,
  Festival: FaStar,
  Conference: FaPeopleCarry,
  Seminar: FaFlag,
  Retreat: FaPeopleArrows,
  Webinar: FaCalendar,
  Show: FaStar,
  Party: FaBirthdayCake,
  Picnic: FaLeaf,
  Class: FaGraduationCap,
  Ceremony: FaMedal,
  Celebration: FaRegSmile,
  Other: FaRegStar,
}

export const allThemes = Object.keys(themeIconMap) as EventThemeName[]
