import type { EventThemeName } from "@/shared/types"
import { IconType } from "react-icons"
import { BsBook, BsCake, BsFilm, BsPersonWalking, BsQuestionCircle } from "react-icons/bs"
import {
  FiBookOpen,
  FiCamera,
  FiCode,
  FiCoffee,
  FiDollarSign,
  FiFeather,
  FiHeart,
  FiImage,
  FiMapPin,
  FiMonitor,
  FiMusic,
  FiShoppingBag,
  FiShoppingCart,
  FiStar,
  FiTrendingUp,
  FiTv,
  FiUsers,
} from "react-icons/fi"
import {
  GiBoxingGlove,
  GiGamepad,
  GiMedal,
  GiMountains,
  GiPaintBrush,
  GiPartyPopper,
  GiPaw,
  GiRecycle,
  GiScissors,
  GiTheaterCurtains,
  GiTrophy,
} from "react-icons/gi"
import { HiOutlineAcademicCap } from "react-icons/hi"
import {
  MdBusinessCenter,
  MdChildCare,
  MdFestival,
  MdFitnessCenter,
  MdFlag,
  MdGroups,
  MdHandshake,
  MdLanguage,
  MdMic,
  MdOutlineBalance,
  MdOutlineChurch,
  MdOutlineFavorite,
  MdOutlineLocalAirport,
  MdOutlineLocalHospital,
  MdOutlineTheaterComedy,
  MdPeople,
  MdRocket,
  MdScience,
  MdSpa,
  MdStore,
} from "react-icons/md"
import { RiPresentationLine, RiRouteLine } from "react-icons/ri"

// Map theme names to their icons (using react-icons)
export const THEME_ICON_MAP: Record<EventThemeName, IconType> = {
  Music: FiMusic,
  Art: GiPaintBrush,
  Sports: GiBoxingGlove,
  Tech: FiMonitor,
  Food: FiCoffee,
  Networking: FiUsers,
  Health: MdOutlineLocalHospital,
  Education: BsBook,
  Business: MdBusinessCenter,
  Nature: FiTrendingUp,
  Travel: MdOutlineLocalAirport,
  Charity: MdOutlineFavorite,
  Fashion: FiShoppingBag,
  Film: BsFilm,
  Photography: FiCamera,
  Literature: FiFeather,
  Science: MdScience,
  Gaming: GiGamepad,
  Spirituality: MdOutlineChurch,
  Family: MdChildCare,
  Comedy: MdOutlineTheaterComedy,
  Dance: FiMusic,
  History: FiBookOpen,
  Politics: MdOutlineBalance,
  Environment: GiRecycle,
  Pets: GiPaw,
  Shopping: FiShoppingCart,
  Fitness: MdFitnessCenter,
  Theater: GiTheaterCurtains,
  Crafts: GiScissors,
  Languages: MdLanguage,
  Social: MdGroups,
  Adventure: GiMountains,
  Startup: MdRocket,
  "Book Club": FiBookOpen,
  Coding: FiCode,
  Volunteering: FiHeart,
  Wellness: MdSpa,
  Exhibition: FiImage,
  Tournament: GiTrophy,
  Workshop: RiPresentationLine,
  Meetup: MdHandshake,
  Lecture: MdMic,
  Hackathon: FiCode,
  Fundraiser: FiDollarSign,
  "Open Mic": MdMic,
  Quiz: BsQuestionCircle,
  Tour: RiRouteLine,
  Market: MdStore,
  Parade: BsPersonWalking,
  Festival: MdFestival,
  Conference: MdFlag,
  Seminar: MdPeople,
  Retreat: FiMapPin,
  Webinar: FiTv,
  Show: FiStar,
  Party: GiPartyPopper,
  Picnic: MdChildCare,
  Class: HiOutlineAcademicCap,
  Ceremony: GiMedal,
  Celebration: BsCake,
  Other: BsQuestionCircle,
}

export const ALL_THEMES: EventThemeName[] = [
  "Music",
  "Art",
  "Sports",
  "Tech",
  "Food",
  "Networking",
  "Health",
  "Education",
  "Business",
  "Nature",
  "Travel",
  "Charity",
  "Fashion",
  "Film",
  "Photography",
  "Literature",
  "Science",
  "Gaming",
  "Spirituality",
  "Family",
  "Comedy",
  "Dance",
  "History",
  "Politics",
  "Environment",
  "Pets",
  "Shopping",
  "Fitness",
  "Theater",
  "Crafts",
  "Languages",
  "Social",
  "Adventure",
  "Startup",
  "Book Club",
  "Coding",
  "Volunteering",
  "Wellness",
  "Exhibition",
  "Tournament",
  "Workshop",
  "Meetup",
  "Lecture",
  "Hackathon",
  "Fundraiser",
  "Open Mic",
  "Quiz",
  "Tour",
  "Market",
  "Parade",
  "Festival",
  "Conference",
  "Seminar",
  "Retreat",
  "Webinar",
  "Show",
  "Party",
  "Picnic",
  "Class",
  "Ceremony",
  "Celebration",
  "Other",
]
