name: Build and deploy ASP.NET Core app to Azure Web App - Plannr

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1) Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Setup .NET 8
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 3) Restore dependencies
      - name: Restore dependencies
        run: dotnet restore
        working-directory: Plannr

      # 4) Build and publish output
      - name: Build and publish
        run: |
          dotnet build --configuration Release --no-restore
          dotnet publish -c Release -o ../publish
        working-directory: Plannr

      # 5) Upload artifact for deploy step
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plannr-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Production
    permissions:
      contents: read

    steps:
      # 1) Download artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: plannr-app
          path: ./publish

      # 2) Deploy directly using Publish Profile
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Plannr'  # brug præcis det navn din App Service har
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
